### ISSUE TITLE
Redirect doesn't occur when you create a new project

### ISSUE THREAD

**Issue by chrisvu27** [codeamp/panel#187]
**Describe the bug**
Redirect doesn't occur when I create a new project

**To Reproduce**
1. Go to `Create`
2. Fill in your `Git Url` `Repo Type` `Project Type`
3. Click `Create`

**Expected behavior**
After you click `Create`, it should redirect the user to the newly created project page

**Comment by aballman** [comment]
Going to close as believe this was same issue as https://github.com/codeamp/panel/issues/168
Both should be fixed as part of https://github.com/codeamp/panel/pull/211
