### ISSUE TITLE
CD doesn't show "CD" for release creator

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#194]
**Describe the bug**
There is a blank field for who created the release when CD deploys a release.

**To Reproduce**
1. Push a commit to a branch that is mapped to an environment in a project with CD turned on
2. See the release creator field in the corresponding release object that is created

**Expected behavior**
It should say "Created by Continuous Delivery/ CD or something that clarifies how it was created"

**Screenshots**
<img width="512" alt="screen shot 2018-07-10 at 3 58 25 pm" src="https://user-images.githubusercontent.com/3188413/42542146-53c3cd0c-845a-11e8-9091-d94409b77cdc.png">

**Desktop (please complete the following information):**
- Chrome Browser

**Comment by aballman** [comment]
Fixed in https://github.com/codeamp/panel/pull/205
