### ISSUE TITLE
Add better validation for services

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#204]
**Describe the bug**
Don't allow service creation if there are spaces, dots or anything that prevents it from being applied with extensions like load balancers.

**To Reproduce**
1. Go to Services in a project.
2. Name it "Foo Boo"
3. Go to extensions and install AWS Load Balancer with the service

**Expected behavior**
Load balancers installs successfully or service page returns validation errors.

**Specific Error Message from Load Balancer**
```
AWS Load Balancer extension (once)
Status
Error: failed to create service: Service "redis.yaml-86893" is invalid: [metadata.name: Invalid value: "foo boo-86893": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'), spec.ports: Required value]
```

**Desktop (please complete the following information):**
 - Chrome Browser

**Comment by amoskyler** [comment]
There are additional characters which need to be validated for. Currently deployments fail if you add a service with underscores `_`. This causes deployment failures with a less than transparent error `Failed to create service`.
