### ISSUE TITLE
Secrets-Version History-Created At is incorrect for 

### ISSUE THREAD

**Issue by WilsonGiese** [codeamp/panel#207]
**Describe the bug**
v2+ updated secret "Created At" value is incorrect, seems to just use the date from v1. 

**To Reproduce**
1. Go to Secrets section of a Project
2. Save at least two versions of one secret

**Expected behavior**
The "Completed At" column for v2 should be the actual creation datetime

**Screenshots**
Secret was updated on July 19th 2018
![screen shot 2018-07-19 at 3 04 25 pm](https://user-images.githubusercontent.com/1562271/42973058-891128b6-8b66-11e8-9bf5-a7d4449945a9.png)

**Desktop (please complete the following information):**
 - Chrome

**Comment by WilsonGiese** [comment]
Also, related most likely, the ordering of rows is not changed when you add a new version -- it seems they're sorted by created date, but should updating secret push it to the top as well?

**Comment by aballman** [comment]
https://github.com/codeamp/panel/issues/214 for your second issue.
Not sure what the status of secrets sorting is so wanted to decouple it from this issue.
