### ISSUE TITLE
Arrow keys don't highlight items in search dropdown

### ISSUE THREAD

**Issue by drshrey** [codeamp/panel#245]
**Describe the bug**
When I use up and down keys to go to a project in the search dropdown, the selected project is not highlighted.

**To Reproduce**
1. Go to search bar
2. Type in a keyword that multiple projects contain
3. Use the arrow keys to go down the list.

**Expected behavior**
I should see a highlight on the item selected.

**Comment by aballman** [comment]
Dupe of #238. Closing.
