### ISSUE TITLE
User can navigate to project pages before selecting environment

### ISSUE THREAD

**Issue by aballman** [codeamp/panel#249]
**Describe the bug**
Once a user lands on {project}/environment they can click on the project links in the left nav.
If they do this before they've selected an environment, then the environment is never reflected in the url. Its ambiguous which environment is selected based on the uri and hard to tell which is inaccurate.

**Comment by drshrey** [comment]
I'm not sure how to reproduce this, can you give an example of how to reproduce this please?

**Comment by drshrey** [comment]
We could solve this by not showing the left nav menu until the person selects an environment for a project. In that way, it could be related to https://github.com/codeamp/panel/issues/250.
