### ISSUE TITLE
Cannot read property 'environments' of undefined after creating new project

### ISSUE THREAD

**Issue by daniel-bryant** [codeamp/panel#333]
**Describe the bug**
Shown a blank page after creating a new project. Viewing the console reveals a Javascript error `Cannot read property 'environments' of undefined`.

**To Reproduce**
1. Go to https://codeamp.checkrhq.net/create
2. Fill in the form and click 'Create'
3. See blank page with console error

**Expected behavior**
I should be directed to the project page without errors.

**Screenshots**
### Immediately after creation
<img width="1437" alt="Screen Shot 2019-04-23 at 2 04 00 PM" src="https://user-images.githubusercontent.com/5214794/56616298-e8cf9800-65d1-11e9-9c14-285c8ccc4501.png">

### After refreshing the page
<img width="1437" alt="Screen Shot 2019-04-23 at 2 12 51 PM" src="https://user-images.githubusercontent.com/5214794/56616304-ec631f00-65d1-11e9-9ebe-c8087c272849.png">

**Desktop (please complete the following information):**
 - Mac OS Chrome

**Additional context**
Might be related to https://github.com/codeamp/panel/issues/283

**Comment by aballman** [comment]
Should be fixed in https://github.com/codeamp/panel/pull/347
